import{AccountMain} from"./account";

export const ACCOUNTSAMP:AccountMain[]=[
    {
        id: 1,
        fname:'Eren',
        lname:'Yeager',
        email:'ErenYeager@gmail.com',
        mobile:'09163127482',
        gender:'Male',
        marital:'Single',
        dateofbirth:'06/12/2022',
        SSS:'1800 10 225 5777',
        tin:'000-123-456-001',
        imgPath: 'assets/account_image/rinrin.webp',
        add:{
            street:'Panadero',
            apt:'12',
            barangay:'Ambiong',
            city:'Baguio City',
            province:'Benguet', 
        } 
    },
    {
        id: 2,
        fname:'Light',
        lname:'Yagami',
        email:'LightYagami@gmail.com',
        mobile:'09163127482',
        gender:'Male',
        marital:'Single',
        dateofbirth:'06/12/2022',
        SSS:'1800 10 225 5777',
        tin:'000-123-456-001',
        imgPath: 'assets/account_image/Light.webp',
        add:{
            street:'Ambiong',
            apt:'12',
            barangay:'Panadero',
            city:'Baguio City',
            province:'Benguet', 
        } 
    },
    {
        id: 3,
        fname:'Itachi',
        lname:'Uchiha',
        email:'ItachiUchiha@gmail.com',
        mobile:'09163127482',
        gender:'Male',
        marital:'Single',
        dateofbirth:'06/12/2022',
        SSS:'1800 10 225 5777',
        tin:'000-123-456-001',
        imgPath: 'assets/account_image/1234.webp',
        add:{
            street:'Ambiong',
            apt:'12',
            barangay:'Panadero',
            city:'Baguio City',
            province:'Benguet', 
        } 
    },
    {
        id: 4,
        fname:'Historia',
        lname:'Reiss',
        email:'HistoriaReiss@gmail.com',
        mobile:'09163127482',
        gender:'Female',
        marital:'Married',
        dateofbirth:'06/12/2022',
        SSS:'1800 10 225 5777',
        tin:'000-123-456-001',
        imgPath: 'assets/account_image/Historia.webp',
        add:{
            street:'Ambiong',
            apt:'12',
            barangay:'Panadero',
            city:'Baguio City',
            province:'Benguet', 
        } 
    },
    {
        id: 5,
        fname:'Mikasa',
        lname:'Ackerman',
        email:'MikasaAckerman@gmail.com',
        mobile:'09163127482',
        gender:'Female',
        marital:'Married',
        dateofbirth:'06/12/2022',
        SSS:'1800 10 225 5777',
        tin:'000-123-456-001',
        imgPath: 'assets/account_image/Mikasa.jpg',
        add:{
            street:'Ambiong',
            apt:'12',
            barangay:'Panadero',
            city:'Baguio City',
            province:'Benguet', 
        } 
    },
    {
        id: 6,
        fname:'Annie',
        lname:'Leonhart',
        email:'AnniLeonhart@gmail.com',
        mobile:'09163127482',
        gender:'Female',
        marital:'single',
        dateofbirth:'06/12/2022',
        SSS:'1800 10 225 5777',
        tin:'000-123-456-001',
        imgPath: 'assets/account_image/Annie.webp',
        add:{
            street:'Ambiong',
            apt:'12',
            barangay:'Panadero',
            city:'Baguio City',
            province:'Benguet', 
        } 
    },
    {
        id: 7,
        fname:'Armin',
        lname:'Arlert',
        email:'ArminArlert@gmail.com',
        mobile:'09163127482',
        gender:'Male',
        marital:'Single',
        dateofbirth:'06/12/2022',
        SSS:'1800 10 225 5777',
        tin:'000-123-456-001',
        imgPath: 'assets/account_image/Armin.webp',
        add:{
            street:'Ambiong',
            apt:'12',
            barangay:'Panadero',
            city:'Baguio City',
            province:'Benguet', 
        } 
    },
    {
        id: 8,
        fname:'Erwin',
        lname:'Smith',
        email:'ErwinSmith@gmail.com',
        mobile:'09163127482',
        gender:'male',
        marital:'Single',
        dateofbirth:'06/12/2022',
        SSS:'1800 10 225 5777',
        tin:'000-123-456-001',
        imgPath: 'assets/account_image/Erwin.webp',
        add:{
            street:'Ambiong',
            apt:'12',
            barangay:'Panadero',
            city:'Baguio City',
            province:'Benguet', 
        } 
    },
    {
        id: 9,
        fname:'Zeke',
        lname:'Yeager',
        email:'ZekeYeager@gmail.com',
        mobile:'09163127482',
        gender:'male',
        marital:'Married',
        dateofbirth:'06/12/2022',
        SSS:'1800 10 225 5777',
        tin:'000-123-456-001',
        imgPath: 'assets/account_image/Zeke.webp',
        add:{
            street:'Ambiong',
            apt:'12',
            barangay:'Panadero',
            city:'Baguio City',
            province:'Benguet', 
        } 
    },
    {
        id: 10,
        fname:'Levi',
        lname:'Ackerman',
        email:'LeviAckerman@gmail.com',
        mobile:'09163127482',
        gender:'male',
        marital:'Single',
        dateofbirth:'06/12/2022',
        SSS:'1800 10 225 5777',
        tin:'000-123-456-001',
        imgPath: 'assets/account_image/lebi.webp',
        add:{
            street:'Ambiong',
            apt:'12',
            barangay:'Panadero',
            city:'Baguio City',
            province:'Benguet', 
        } 
    }
]